### ISSUE TITLE
download csv for filtered studies

### ISSUE THREAD

**Issue by stephenturner** [leekgroup/recount-website#2]
feature request: add a download csv button for list of filtered studies displayed on the shiny app

----

collab: "hey, can you find some public data to look at X?"

me: "sure."

(5 minutes passes)

me: "here's a spreadsheet. what looks interesting to you?"

etc.

**Comment by lcolladotor** [comment]
Hi Stephen,

Thanks for the feedback!

Would a "download all studies" button also be of interest? Well, I guess that you could download them all if you don't filter any.

I'll look into this next week (on vacations right now ^_^)

Best,
Leonardo

**Comment by stephenturner** [comment]
Sure! Just exporting (all rows of) the table of search results would be
imminently useful.

**Comment by jtleek** [comment]
Agreed this should just be a downloadable csv

**Comment by lcolladotor** [comment]
Hi Stephen,

Let me know what you think.

Best,
Leo

**Comment by stephenturner** [comment]
👍  thanks!

Only comment on the UI/UX front -- I, like others I'm sure, hit buttons and run code before reading documentation. I hit the download button a few times only to get 10 results, before I read the little instruction sheet to change the display. To do that, I had to find it (where is it?), scroll up to the top, then scroll all the way back to the bottom to hit the download button again. Better to either (a) always export all studies, or (b) duplicate the "show x entries" dropdown below the table. Looks like you might be using **DT**, and fully realize this might not be an option you can set without hacking into the JS code.

**Comment by lcolladotor** [comment]
Hi Stephen,

According to http://rstudio.github.io/DT/shiny.html section 2.2 `input$tableId_rows_all` should be what I need, but it doesn't work on the server side as documented on the example `system.file('examples', 'DT-info', package = 'DT')`. So I can't get use `DT` to get all the rows matching the search (versus only the displayed ones). 

I'll check if I can get the "show x entries" dropdown to show twice.

Best,
Leo

**Comment by lcolladotor** [comment]
Hi Stephen,

It turns out that I was using a slightly older `DT` version. Version 0.2 fixes the issue I mentioned in my previous comment about `input$tableId_rows_all`, so it's working now.

I also tried out the `Buttons` extension described at http://rstudio.github.io/DT/extensions.html and further discussed at https://github.com/rstudio/DT/issues/213#issuecomment-233793448. While it's easy to code and offers different formats, it again would only be able to download the data that is currently displayed with server-side processing. Which is why I'm not going to use the `Buttons` extension.

Best,
Leo

**Comment by stephenturner** [comment]
Nice, thanks! 🙇

**Comment by lcolladotor** [comment]
No problem and thank you for the feature request!
